DROP TABLE IF EXISTS "CHANNEL";

DROP TABLE IF EXISTS "FEED_ITEM";

CREATE TABLE "CHANNEL" (
	"ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
	"LINK" TEXT NOT NULL
);

CREATE TABLE "FEED_ITEM" (
	"ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
	"CHANNEL_ID" BIGINT NOT NULL,
	"TITLE" TEXT NOT NULL,
	"AUTHOR" TEXT,
	"CATEGORY" TEXT,
	"DESCRIPTION" TEXT NOT NULL,
	"GUID" TEXT NOT NULL UNIQUE,
	"IS_PERMA_LINK" TEXT NOT NULL,
	"LINK" TEXT NOT NULL,
	"PUB_DATE" TEXT NOT NULL
);

CREATE TABLE "FEED_ITEM_SYNC_EVENT" (
	"ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
	"ACTION" TEXT NOT NULL check (action in ('I','D','U')),
	"FEED_ITEM_ID" BIGINT NOT NULL
);
