CREATE TABLE "CHANNEL" (
	"ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
	"LINK" TEXT NOT NULL
);

CREATE TABLE "FEED_ITEM" (
	"ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
	"CHANNEL_ID" BIGINT NOT NULL,
	"TITLE" TEXT NOT NULL,
	"AUTHOR" TEXT,
	"CATEGORY" TEXT,
	"DESCRIPTION" TEXT,
	"GUID" TEXT NOT NULL UNIQUE,
	"IS_PERMA_LINK" TEXT NOT NULL,
	"LINK" TEXT,
	"PUB_DATE" TEXT NOT NULL,
	"PROCESSED" BOOLEAN NOT NULL DEFAULT FALSE
);
